// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_M8NnUMrOpqQrnQFn2XWmwHuhLJG5Wfc',
    appId: '1:605601028430:web:98d3a429f468be158ca61f',
    messagingSenderId: '605601028430',
    projectId: 'aurora-sc',
    authDomain: 'aurora-sc.firebaseapp.com',
    storageBucket: 'aurora-sc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDB_zDVz28sncZo8qyE2wOFtco7rUGcK4',
    appId: '1:605601028430:android:b710b57e71057a908ca61f',
    messagingSenderId: '605601028430',
    projectId: 'aurora-sc',
    storageBucket: 'aurora-sc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArNdCfQl_BCIIel-fF5IWeSHjjkEt6Ais',
    appId: '1:605601028430:ios:b8b9b5cf0edd54538ca61f',
    messagingSenderId: '605601028430',
    projectId: 'aurora-sc',
    storageBucket: 'aurora-sc.appspot.com',
    iosClientId: '605601028430-3he182dhgif1plcvjkm9g3o4tsu2dmf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurora',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArNdCfQl_BCIIel-fF5IWeSHjjkEt6Ais',
    appId: '1:605601028430:ios:b8b9b5cf0edd54538ca61f',
    messagingSenderId: '605601028430',
    projectId: 'aurora-sc',
    storageBucket: 'aurora-sc.appspot.com',
    iosClientId: '605601028430-3he182dhgif1plcvjkm9g3o4tsu2dmf9.apps.googleusercontent.com',
    iosBundleId: 'com.example.aurora',
  );
}
